# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fmarcolo/Documents/rogue_jam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fmarcolo/Documents/rogue_jam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmarcolo/Documents/rogue_jam/CMakeFiles /home/fmarcolo/Documents/rogue_jam//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmarcolo/Documents/rogue_jam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rogue

# Build rule for target.
rogue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rogue
.PHONY : rogue

# fast build rule for target.
rogue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/build
.PHONY : rogue/fast

src/Dungeons/BleachDungeon.o: src/Dungeons/BleachDungeon.cpp.o
.PHONY : src/Dungeons/BleachDungeon.o

# target to build an object file
src/Dungeons/BleachDungeon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/BleachDungeon.cpp.o
.PHONY : src/Dungeons/BleachDungeon.cpp.o

src/Dungeons/BleachDungeon.i: src/Dungeons/BleachDungeon.cpp.i
.PHONY : src/Dungeons/BleachDungeon.i

# target to preprocess a source file
src/Dungeons/BleachDungeon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/BleachDungeon.cpp.i
.PHONY : src/Dungeons/BleachDungeon.cpp.i

src/Dungeons/BleachDungeon.s: src/Dungeons/BleachDungeon.cpp.s
.PHONY : src/Dungeons/BleachDungeon.s

# target to generate assembly for a file
src/Dungeons/BleachDungeon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/BleachDungeon.cpp.s
.PHONY : src/Dungeons/BleachDungeon.cpp.s

src/Dungeons/Dungeon.o: src/Dungeons/Dungeon.cpp.o
.PHONY : src/Dungeons/Dungeon.o

# target to build an object file
src/Dungeons/Dungeon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/Dungeon.cpp.o
.PHONY : src/Dungeons/Dungeon.cpp.o

src/Dungeons/Dungeon.i: src/Dungeons/Dungeon.cpp.i
.PHONY : src/Dungeons/Dungeon.i

# target to preprocess a source file
src/Dungeons/Dungeon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/Dungeon.cpp.i
.PHONY : src/Dungeons/Dungeon.cpp.i

src/Dungeons/Dungeon.s: src/Dungeons/Dungeon.cpp.s
.PHONY : src/Dungeons/Dungeon.s

# target to generate assembly for a file
src/Dungeons/Dungeon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/Dungeon.cpp.s
.PHONY : src/Dungeons/Dungeon.cpp.s

src/Dungeons/DungeonManager.o: src/Dungeons/DungeonManager.cpp.o
.PHONY : src/Dungeons/DungeonManager.o

# target to build an object file
src/Dungeons/DungeonManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/DungeonManager.cpp.o
.PHONY : src/Dungeons/DungeonManager.cpp.o

src/Dungeons/DungeonManager.i: src/Dungeons/DungeonManager.cpp.i
.PHONY : src/Dungeons/DungeonManager.i

# target to preprocess a source file
src/Dungeons/DungeonManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/DungeonManager.cpp.i
.PHONY : src/Dungeons/DungeonManager.cpp.i

src/Dungeons/DungeonManager.s: src/Dungeons/DungeonManager.cpp.s
.PHONY : src/Dungeons/DungeonManager.s

# target to generate assembly for a file
src/Dungeons/DungeonManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Dungeons/DungeonManager.cpp.s
.PHONY : src/Dungeons/DungeonManager.cpp.s

src/Scenes/HomeScene.o: src/Scenes/HomeScene.cpp.o
.PHONY : src/Scenes/HomeScene.o

# target to build an object file
src/Scenes/HomeScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/HomeScene.cpp.o
.PHONY : src/Scenes/HomeScene.cpp.o

src/Scenes/HomeScene.i: src/Scenes/HomeScene.cpp.i
.PHONY : src/Scenes/HomeScene.i

# target to preprocess a source file
src/Scenes/HomeScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/HomeScene.cpp.i
.PHONY : src/Scenes/HomeScene.cpp.i

src/Scenes/HomeScene.s: src/Scenes/HomeScene.cpp.s
.PHONY : src/Scenes/HomeScene.s

# target to generate assembly for a file
src/Scenes/HomeScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/HomeScene.cpp.s
.PHONY : src/Scenes/HomeScene.cpp.s

src/Scenes/MenuScene.o: src/Scenes/MenuScene.cpp.o
.PHONY : src/Scenes/MenuScene.o

# target to build an object file
src/Scenes/MenuScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/MenuScene.cpp.o
.PHONY : src/Scenes/MenuScene.cpp.o

src/Scenes/MenuScene.i: src/Scenes/MenuScene.cpp.i
.PHONY : src/Scenes/MenuScene.i

# target to preprocess a source file
src/Scenes/MenuScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/MenuScene.cpp.i
.PHONY : src/Scenes/MenuScene.cpp.i

src/Scenes/MenuScene.s: src/Scenes/MenuScene.cpp.s
.PHONY : src/Scenes/MenuScene.s

# target to generate assembly for a file
src/Scenes/MenuScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/MenuScene.cpp.s
.PHONY : src/Scenes/MenuScene.cpp.s

src/Scenes/Scene.o: src/Scenes/Scene.cpp.o
.PHONY : src/Scenes/Scene.o

# target to build an object file
src/Scenes/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/Scene.cpp.o
.PHONY : src/Scenes/Scene.cpp.o

src/Scenes/Scene.i: src/Scenes/Scene.cpp.i
.PHONY : src/Scenes/Scene.i

# target to preprocess a source file
src/Scenes/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/Scene.cpp.i
.PHONY : src/Scenes/Scene.cpp.i

src/Scenes/Scene.s: src/Scenes/Scene.cpp.s
.PHONY : src/Scenes/Scene.s

# target to generate assembly for a file
src/Scenes/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/Scene.cpp.s
.PHONY : src/Scenes/Scene.cpp.s

src/Scenes/SceneManager.o: src/Scenes/SceneManager.cpp.o
.PHONY : src/Scenes/SceneManager.o

# target to build an object file
src/Scenes/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/SceneManager.cpp.o
.PHONY : src/Scenes/SceneManager.cpp.o

src/Scenes/SceneManager.i: src/Scenes/SceneManager.cpp.i
.PHONY : src/Scenes/SceneManager.i

# target to preprocess a source file
src/Scenes/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/SceneManager.cpp.i
.PHONY : src/Scenes/SceneManager.cpp.i

src/Scenes/SceneManager.s: src/Scenes/SceneManager.cpp.s
.PHONY : src/Scenes/SceneManager.s

# target to generate assembly for a file
src/Scenes/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Scenes/SceneManager.cpp.s
.PHONY : src/Scenes/SceneManager.cpp.s

src/Sprite/Sprite.o: src/Sprite/Sprite.cpp.o
.PHONY : src/Sprite/Sprite.o

# target to build an object file
src/Sprite/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Sprite/Sprite.cpp.o
.PHONY : src/Sprite/Sprite.cpp.o

src/Sprite/Sprite.i: src/Sprite/Sprite.cpp.i
.PHONY : src/Sprite/Sprite.i

# target to preprocess a source file
src/Sprite/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Sprite/Sprite.cpp.i
.PHONY : src/Sprite/Sprite.cpp.i

src/Sprite/Sprite.s: src/Sprite/Sprite.cpp.s
.PHONY : src/Sprite/Sprite.s

# target to generate assembly for a file
src/Sprite/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Sprite/Sprite.cpp.s
.PHONY : src/Sprite/Sprite.cpp.s

src/Sprite/SpriteManager.o: src/Sprite/SpriteManager.cpp.o
.PHONY : src/Sprite/SpriteManager.o

# target to build an object file
src/Sprite/SpriteManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Sprite/SpriteManager.cpp.o
.PHONY : src/Sprite/SpriteManager.cpp.o

src/Sprite/SpriteManager.i: src/Sprite/SpriteManager.cpp.i
.PHONY : src/Sprite/SpriteManager.i

# target to preprocess a source file
src/Sprite/SpriteManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Sprite/SpriteManager.cpp.i
.PHONY : src/Sprite/SpriteManager.cpp.i

src/Sprite/SpriteManager.s: src/Sprite/SpriteManager.cpp.s
.PHONY : src/Sprite/SpriteManager.s

# target to generate assembly for a file
src/Sprite/SpriteManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Sprite/SpriteManager.cpp.s
.PHONY : src/Sprite/SpriteManager.cpp.s

src/Text/Text.o: src/Text/Text.cpp.o
.PHONY : src/Text/Text.o

# target to build an object file
src/Text/Text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Text/Text.cpp.o
.PHONY : src/Text/Text.cpp.o

src/Text/Text.i: src/Text/Text.cpp.i
.PHONY : src/Text/Text.i

# target to preprocess a source file
src/Text/Text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Text/Text.cpp.i
.PHONY : src/Text/Text.cpp.i

src/Text/Text.s: src/Text/Text.cpp.s
.PHONY : src/Text/Text.s

# target to generate assembly for a file
src/Text/Text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Text/Text.cpp.s
.PHONY : src/Text/Text.cpp.s

src/Text/TextManager.o: src/Text/TextManager.cpp.o
.PHONY : src/Text/TextManager.o

# target to build an object file
src/Text/TextManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Text/TextManager.cpp.o
.PHONY : src/Text/TextManager.cpp.o

src/Text/TextManager.i: src/Text/TextManager.cpp.i
.PHONY : src/Text/TextManager.i

# target to preprocess a source file
src/Text/TextManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Text/TextManager.cpp.i
.PHONY : src/Text/TextManager.cpp.i

src/Text/TextManager.s: src/Text/TextManager.cpp.s
.PHONY : src/Text/TextManager.s

# target to generate assembly for a file
src/Text/TextManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/Text/TextManager.cpp.s
.PHONY : src/Text/TextManager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rogue.dir/build.make CMakeFiles/rogue.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rogue"
	@echo "... src/Dungeons/BleachDungeon.o"
	@echo "... src/Dungeons/BleachDungeon.i"
	@echo "... src/Dungeons/BleachDungeon.s"
	@echo "... src/Dungeons/Dungeon.o"
	@echo "... src/Dungeons/Dungeon.i"
	@echo "... src/Dungeons/Dungeon.s"
	@echo "... src/Dungeons/DungeonManager.o"
	@echo "... src/Dungeons/DungeonManager.i"
	@echo "... src/Dungeons/DungeonManager.s"
	@echo "... src/Scenes/HomeScene.o"
	@echo "... src/Scenes/HomeScene.i"
	@echo "... src/Scenes/HomeScene.s"
	@echo "... src/Scenes/MenuScene.o"
	@echo "... src/Scenes/MenuScene.i"
	@echo "... src/Scenes/MenuScene.s"
	@echo "... src/Scenes/Scene.o"
	@echo "... src/Scenes/Scene.i"
	@echo "... src/Scenes/Scene.s"
	@echo "... src/Scenes/SceneManager.o"
	@echo "... src/Scenes/SceneManager.i"
	@echo "... src/Scenes/SceneManager.s"
	@echo "... src/Sprite/Sprite.o"
	@echo "... src/Sprite/Sprite.i"
	@echo "... src/Sprite/Sprite.s"
	@echo "... src/Sprite/SpriteManager.o"
	@echo "... src/Sprite/SpriteManager.i"
	@echo "... src/Sprite/SpriteManager.s"
	@echo "... src/Text/Text.o"
	@echo "... src/Text/Text.i"
	@echo "... src/Text/Text.s"
	@echo "... src/Text/TextManager.o"
	@echo "... src/Text/TextManager.i"
	@echo "... src/Text/TextManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

